"""
Generates the donation receipt/bill as a PDF, in-memory (no file written to
disk). Uses reportlab with a bundled DejaVu Sans font so the ₹ symbol and
Tamil-adjacent punctuation render correctly regardless of what fonts are
installed on the server.
"""

from io import BytesIO
from pathlib import Path

from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A5
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

FONTS_DIR = Path(__file__).resolve().parent / "fonts"

_FONTS_REGISTERED = False


def _register_fonts():
    """Register the bundled DejaVu fonts with reportlab, once per process."""
    global _FONTS_REGISTERED
    if _FONTS_REGISTERED:
        return

    pdfmetrics.registerFont(TTFont("DejaVuSans", str(FONTS_DIR / "DejaVuSans.ttf")))
    pdfmetrics.registerFont(TTFont("DejaVuSans-Bold", str(FONTS_DIR / "DejaVuSans-Bold.ttf")))
    _FONTS_REGISTERED = True


def generate_donation_receipt_pdf(donation, festival_info) -> BytesIO:
    """
    Build a single-page A5 receipt/bill for one Donation and return it as
    an in-memory BytesIO ready to be written to an HttpResponse or merged
    with other receipts via pypdf.
    """

    _register_fonts()

    buffer = BytesIO()
    width, height = A5
    c = canvas.Canvas(buffer, pagesize=A5)

    margin = 15 * mm
    x = margin
    y = height - margin

    # ---- Letterhead ----
    c.setFont("DejaVuSans-Bold", 16)
    c.setFillColor(colors.HexColor("#253d29"))
    c.drawString(x, y, festival_info.festival_name or "Thiraviya Nagar Temple Festival")
    y -= 8 * mm

    c.setFont("DejaVuSans", 9)
    c.setFillColor(colors.HexColor("#526d39"))
    contact_line_parts = [
        part
        for part in [
            festival_info.temple_address,
            festival_info.contact_phone,
            festival_info.contact_email,
        ]
        if part
    ]
    if contact_line_parts:
        c.drawString(x, y, "  |  ".join(contact_line_parts))
        y -= 6 * mm

    if festival_info.pan_number:
        c.drawString(x, y, f"PAN: {festival_info.pan_number}")
        y -= 6 * mm

    y -= 2 * mm
    c.setStrokeColor(colors.HexColor("#253d29"))
    c.setLineWidth(1)
    c.line(x, y, width - margin, y)
    y -= 10 * mm

    # ---- Title ----
    c.setFont("DejaVuSans-Bold", 13)
    c.setFillColor(colors.HexColor("#20251f"))
    c.drawCentredString(width / 2, y, "DONATION RECEIPT")
    y -= 10 * mm

    # ---- Receipt meta (number + date) ----
    c.setFont("DejaVuSans", 10)
    c.drawString(x, y, f"Receipt No: {donation.receipt_number}")
    local_dt = timezone.localtime(donation.created_at)
    c.drawRightString(width - margin, y, f"Date: {local_dt.strftime('%d %b %Y, %I:%M %p')}")
    y -= 10 * mm

    # ---- Donor details box ----
    c.setFont("DejaVuSans-Bold", 10)
    c.drawString(x, y, "Received with thanks from:")
    y -= 7 * mm

    c.setFont("DejaVuSans", 10)
    c.drawString(x, y, f"Name: {donation.name}")
    y -= 6 * mm
    c.drawString(x, y, f"Mobile: {donation.mobile}")
    y -= 6 * mm

    address_lines = _wrap_text(f"Address: {donation.address}", max_chars=58)
    for line in address_lines:
        c.drawString(x, y, line)
        y -= 6 * mm

    y -= 4 * mm

    # ---- Amount box ----
    c.setFillColor(colors.HexColor("#e8ecdf"))
    c.roundRect(x, y - 14 * mm, width - 2 * margin, 14 * mm, 3, stroke=0, fill=1)

    c.setFillColor(colors.HexColor("#253d29"))
    c.setFont("DejaVuSans-Bold", 11)
    c.drawString(x + 5 * mm, y - 6 * mm, "Amount Donated")

    c.setFont("DejaVuSans-Bold", 16)
    c.drawRightString(
        width - margin - 5 * mm,
        y - 9 * mm,
        f"\u20b9 {donation.amount:,.2f}",
    )
    y -= 22 * mm

    # ---- Demo / provisional notice ----
    if donation.is_demo:
        c.setFillColor(colors.HexColor("#a33b3b"))
        c.setFont("DejaVuSans-Bold", 8)
        notice = (
            "This is a provisional acknowledgement generated by the website demo. "
            "No payment has been processed and this is not a valid proof of "
            "payment or tax exemption."
        )
        for line in _wrap_text(notice, max_chars=70):
            c.drawString(x, y, line)
            y -= 4.5 * mm
        y -= 4 * mm

    # ---- Footer ----
    c.setStrokeColor(colors.HexColor("#dfe5d7"))
    c.line(x, y, width - margin, y)
    y -= 8 * mm

    c.setFillColor(colors.HexColor("#667064"))
    c.setFont("DejaVuSans", 8)
    c.drawCentredString(width / 2, y, "Thank you for supporting our temple festival.")

    c.showPage()
    c.save()

    buffer.seek(0)
    return buffer


def _wrap_text(text, max_chars=60):
    """Very small word-wrapper so long addresses/notices don't run off the page."""
    words = text.split()
    lines = []
    current = ""

    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > max_chars and current:
            lines.append(current)
            current = word
        else:
            current = candidate

    if current:
        lines.append(current)

    return lines
